/**
 * This file is autogenerated by Scaffold-Stark.
 * You should not edit it manually or your changes might be overwritten.
 */

const deployedContracts = {
  devnet: {
    YourContract: {
      address:
        "0x1fc4fdab3c1ec0b3a217bcec6e28a64a764726f8f4afac69ab19fad0658a23d",
      abi: [
        {
          type: "constructor",
          name: "constructor",
          inputs: [],
        },
        {
          type: "function",
          name: "add_participant",
          inputs: [
            {
              name: "name",
              type: "core::felt252",
            },
          ],
          outputs: [],
          state_mutability: "external",
        },
        {
          type: "struct",
          name: "core::integer::u256",
          members: [
            {
              name: "low",
              type: "core::integer::u128",
            },
            {
              name: "high",
              type: "core::integer::u128",
            },
          ],
        },
        {
          type: "function",
          name: "draw_winner",
          inputs: [
            {
              name: "seed",
              type: "core::integer::u256",
            },
          ],
          outputs: [
            {
              type: "core::felt252",
            },
          ],
          state_mutability: "view",
        },
        {
          type: "event",
          name: "contracts::YourContract::YourContract::Event",
          kind: "enum",
          variants: [],
        },
      ],
      classHash:
        "0x2a2397665260c8b4c2a64e3c852e687b0d2bab55c04c193d31205e49b2ac4a3",
    },
  },
  sepolia: {
    YourContract: {
      address:
        "0x638358bb6daa07f3a80fa27c768e97de2628bb33fce38275ff7c45c4028d844",
      abi: [
        {
          type: "constructor",
          name: "constructor",
          inputs: [],
        },
        {
          type: "function",
          name: "add_participant",
          inputs: [
            {
              name: "name",
              type: "core::felt252",
            },
          ],
          outputs: [],
          state_mutability: "external",
        },
        {
          type: "struct",
          name: "core::integer::u256",
          members: [
            {
              name: "low",
              type: "core::integer::u128",
            },
            {
              name: "high",
              type: "core::integer::u128",
            },
          ],
        },
        {
          type: "function",
          name: "draw_winner",
          inputs: [
            {
              name: "seed",
              type: "core::integer::u256",
            },
          ],
          outputs: [
            {
              type: "core::felt252",
            },
          ],
          state_mutability: "view",
        },
        {
          type: "event",
          name: "contracts::YourContract::YourContract::Event",
          kind: "enum",
          variants: [],
        },
      ],
      classHash:
        "0x2a2397665260c8b4c2a64e3c852e687b0d2bab55c04c193d31205e49b2ac4a3",
    },
  },
} as const;

export default deployedContracts;
